apiVersion: v1
kind: Pod
metadata: 
  name: lbpod
  labels:
    app: lbpod
spec:
  containers:
  - name: httpd-cont
    image: httpd:latest
    ports:
      - name: httpdport
        containerPort: 80
...
---
apiVersion: v1
kind: Service
metadata:
  name: lbsvc
  labels:
    app: lbpod
spec:
  type: LoadBalancer
  selector:
    app: lbpod
  ports:
    port: 80
    targetPort: 80